version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      aws-sdk: { patterns: ["@aws-sdk/*"] }
      cdk: { patterns: ["aws-cdk", "aws-cdk-lib", "constructs"] }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
